# Testing
deployment:
  domain: andrewmyshok.com
  ports:
    port: 8080
    protocol: tcp
  ssl:
    directories:
      cert: ${HOME}/portfolio/certs
      key: ${HOME}/portfolio/private
      acme-challenge: /etc/nginx/acme/.well-known/acme-challenge