# Testing
deployment:
  domain: andrewmyshok.com
  ports:
    port: 8080
    protocol: tcp
  ssl:
    directories:
      cert: /etc/ssl/certs
      key: /etc/ssl/private
      acme-challenge: /etc/nginx/acme/.well-known/acme-challenge