# Testing
deployment:
  domain: andrewmyshok.com
  ports:
    port: 8080
    protocol: tcp
  ssl:
    directories:
      cert: nginx/certificates
      key: nginx/private
      acme-challenge: /etc/nginx/acme/.well-known/acme-challenge