# Testing
deployment:
  domain: andrewmyshok.com
  ports:
    port: 8080
    protocol: tcp
  ssl:
    directories: #paths are relative
      cert: nginx/certificates/
      key: nginx/private/
      acme-challenge: nginx/acme/