# Testing
deployment:
  domain: andrewmyshok.com
  ports:
    port: 8080
    protocol: tcp
  ssl:
    directories:
      cert: /portfolio/nginx/certificates/
      key: /portfolio/nginx/private/
      acme-challenge: /portfolio/nginx/acme/
