# Testing
deployment:
  domain: andrewmyshok.com
  ports:
    port: 8080
    protocol: tcp
  ssl:
    template: ssl.conf
    directories:
      cert: /etc/nginx/certificates/
      key: /etc/nginx/private/
      acme-challenge: /var/www/${DOMAIN}/
