name: Deploy App to Dev Server

on:
  push:
#  paths: ['envs/testing/settings.yml', 'envs/testing/deployment.yml']
  repository_dispatch:
    types: [pr-merged-to-main]

permissions:
  contents: write

jobs:
  Get-Domain:
    runs-on: ubuntu-latest

    outputs:
      domain: ${{ steps.domain-name.outputs.name }}

    steps:
      - name: setup yq
        uses: mikefarah/yq@master

      - name: checkout repo
        uses: actions/checkout@v4

      - name: grab domain name
        id: domain-name
        run: |
          BASE_DOMAIN=$(yq '.deployment.domain' $BASE_SETTINGS_FILE)
          SUB_DOMAIN=$(yq '.specifics | load(.deployment) | .app.subdomain' $ENV_SETTINGS_FILE)
          if [[ ! -z $SUB_DOMAIN ]]; then
            SUB_DOMAIN="$SUB_DOMAIN."
          fi
          echo "name=${SUB_DOMAIN}${BASE_DOMAIN}" >> "$GITHUB_OUTPUT"

        env:
          BASE_SETTINGS_FILE: base/settings.yml
          ENV_SETTINGS_FILE: envs/testing/settings.yml

  Get-EC2-IP:
    runs-on: ubuntu-latest

    outputs:
      ec2-ip: ${{ steps.get-ip.outputs.EC2_IP }}

    # This is required for requesting the JWT from AWS
    permissions:
      id-token: write 

    env:
      DEV_SETTINGS_FOLDER: "envs/testing"

    steps:
      - name: setup yq
        uses: mikefarah/yq@master

      - name: checkout repo
        uses: actions/checkout@v4

      - name: get aws region
        run: |
          cd $DEV_SETTINGS_FOLDER
          AWS_ZONE=$(yq '.app.aws-zone' deployment.yml)
          echo "AWS_ZONE=$AWS_ZONE" >> "$GITHUB_ENV"
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_ZONE }}
          role-to-assume: arn:aws:iam::822477694772:role/Github-Actions

      - name: get ec2 ip
        id: get-ip
        run: |
          EC2_IP=$(aws --region "$AWS_ZONE" \
          ec2 describe-instances --filters \
          "Name=instance-state-name, Values=running" \
          "Name=instance-id, Values=${{ secrets.EC2_INSTANCE_ID_DEV }}" \
          --query "Reservations[*].Instances[*].[PublicIpAddress]" \
          --output text)
          echo "EC2_IP=$EC2_IP" >> "$GITHUB_OUTPUT"
    
  EC2-Deploy:
    runs-on: ubuntu-latest
    needs: [Get-EC2-IP, Get-Domain]

    # For this deploy to work correctly, the EC2 instance needs to have docker and docker-compose installed
    # Then make sure the docker daemon is running
    # Also make sure to create a docker group on the EC2 instance before running docker commands, otherwise
    # the EC2 instance won't have permissions for those docker commands (without using sudo for linux)

    outputs:
      build: ${{ steps.version-outputs.outputs.BUILD }}
      version: ${{ steps.version-outputs.outputs.VERSION }}

    env:
      ENV_CONFIG_FILE: envs/testing/settings.yml
      APP_REPO_CHECKOUT_PATH: app
      EC2_USERNAME: ${{ secrets.EC2_USERNAME_DEV }}
      EC2_IP: ${{ needs.Get-EC2-IP.outputs.ec2-ip }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: setup yq
        uses: mikefarah/yq@master

      - name: checkout repo
        uses: actions/checkout@v4

      - name: checkout app repo file
        uses: actions/checkout@v4
        with:
          repository: "Kojolika/Portfolio"
          path: ${{ env.APP_REPO_CHECKOUT_PATH }}
          ref: "main"

      - name: get port and protocol settings
        run: |
          echo -n "PORT=" >> "$GITHUB_ENV" && yq 'load(.resources[0]) | .deployment.ports.port' $ENV_CONFIG_FILE >> "$GITHUB_ENV"
          echo -n "AWS_ZONE=" >> "$GITHUB_ENV" && yq '.specifics | load(.deployment) | .app.aws-zone' $ENV_CONFIG_FILE >> "$GITHUB_ENV"
          echo -n "NODE_ENV=" >> "$GITHUB_ENV" && yq '.specifics | load(.deployment) | .app.environment' $ENV_CONFIG_FILE >> "$GITHUB_ENV"

      - name: get build and verison number
        run: |
          IMAGE=$(yq 'load(.specifics.version) | .spec.containers[] | select(.app-name == "portfolio") | .image' $ENV_CONFIG_FILE)
          echo -n "IMAGE=" >> "$GITHUB_ENV" && echo "$IMAGE" >> "$GITHUB_ENV"
          if [[ -z $(echo "$IMAGE" | grep -P -o "[0-9]+\.[0-9]+\.[0-9]+\-[0-9]+") ]]; then
              if [ ! "$IMAGE" = "latest"]; then
                exit 1;
              fi
            ACCESS_TOKEN=$(curl https://hub.docker.com/v2/users/login -d "username=$DOCKER_USERNAME" -d "password=$DOCKER_PASSWORD" | yq '.token')
            echo "::add-mask::$ACCESS_TOKEN"
            REPO_RESULTS=$(curl https://hub.docker.com/v2/namespaces/myshoka/repositories/portfolio/tags -H "Authorization: Bearer $ACCESS_TOKEN")
            echo "::add-mask::$REPO_RESULTS"
            LATEST_SHA=$(echo "$REPO_RESULTS" | image="$IMAGE" yq '.results[] | select(.name == env(image)) | .digest')
            echo "::add-mask::$LATEST_SHA"
            LATEST_VERSION=$(echo "$REPO_RESULTS" | latest_sha="$LATEST_SHA" image="$IMAGE" yq '.results[] | select(.digest == env(latest_sha) and .name != env(image)) | .name')
            echo "::add-mask::$LATEST_VERSION"

            echo -n "VERSION=" >> "$GITHUB_ENV" && echo "$LATEST_VERSION" |  grep -P -o "[0-9]+\.[0-9]+\.[0-9]+" >> "$GITHUB_ENV"
            echo -n "BUILD=" >> "$GITHUB_ENV" && echo "$LATEST_VERSION" |  grep -P -o "(?<=\-)[0-9]+" >> "$GITHUB_ENV"
          else
            echo -n "VERSION=" >> "$GITHUB_ENV" && echo "$IMAGE" |  grep -P -o "[0-9]+\.[0-9]+\.[0-9]+" >> "$GITHUB_ENV"
            echo -n "BUILD=" >> "$GITHUB_ENV" && echo "$IMAGE" |  grep -P -o "(?<=\-)[0-9]+" >> "$GITHUB_ENV"
          fi
      
      - name: add version and build to job outputs
        id: version-outputs
        run: |
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "BUILD=$BUILD" >> "$GITHUB_OUTPUT"
      
      - name: hide EC2 ip
        run: |
          echo "::add-mask::$EC2_IP"

      - name: set ssh identity on github runner
        run: |
          SSH_DIR=~/.ssh
          mkdir -p $SSH_DIR
          chmod 700 $SSH_DIR
          cd $SSH_DIR
          ssh-keyscan $EC2_IP > known_hosts
          echo "$SSH_KEY" > $SSH_PRIVATE_KEY_FILE
          chmod 600 *
          eval `ssh-agent -s`
          ssh-add ${SSH_DIR}/${SSH_PRIVATE_KEY_FILE}

        env:
          SSH_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          SSH_PRIVATE_KEY_FILE: id_rsa

      - name: set env variables for docker-compose
        run: |
          cd ${GITHUB_WORKSPACE}
          cd $APP_REPO_CHECKOUT_PATH
          echo "NODE_ENV=$NODE_ENV" >> .env
          echo "PORT=$PORT" >> .env
          echo "AWS_ZONE=$AWS_ZONE" >> .env
          echo "BUILD=${VERSION}+${BUILD}" >> .env
          echo "LATEST_IMAGE=${DOCKER_REPO}:${IMAGE}" >> .env
          echo "DOMAIN=${DOMAIN}" >> .env
          
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO_URL }}
          DOMAIN: ${{ needs.Get-Domain.outputs.domain }}
 
      - name: run commands on ec2 through ssh
        run: |
          cd $APP_REPO_CHECKOUT_PATH
          docker context create $EC2_CONTEXT --docker "host=ssh://${EC2_USERNAME}@${EC2_IP}"
          docker context use $EC2_CONTEXT
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
          docker-compose down
          docker system prune -a -f
          docker-compose up -d

        env:
          EC2_CONTEXT: ec2

      - name: check if both containers are running
        # We subtract 1 since we're counting the lines of the stdin, the first line is the table header
        run: |
          NUM_CONTAINERS=$(($(docker ps | wc -l) - 1))
          if(( NUM_CONTAINERS < 2 )); then
            exit 1;
          fi
  
  Check-HTTPS:
    runs-on: ubuntu-latest
    needs: [EC2-Deploy, Get-Domain]

    env:
      KEY_DIRECTORY: "/etc/pki/tls/private/"
      KEY_NAME: server.key
      CRS_NAME: csr.pem

    steps:
      - name: check if https is enabled
        id: https-check
        run: |
          if wget --spider https://${EC2_IP} 2> /dev/null; then 
            HTTPS_ENABLED="true"
          else
            HTTPS_ENABLED="false"
          fi
          echo "HTTPS_ENABLED=$HTTPS_ENABLED" >> "$GITHUB_OUTPUT"
        
        env:
          EC2_IP: ${{ needs.Get-EC2-IP.outputs.ec2-ip }}

      - name: create rsa key
        if: ${{ steps.https-check.outputs.HTTPS_ENABLED == 'false' }}
        run: |
          cd $KEY_DIRECTORY
          sudo openssl genrsa -aes128 -passout pass:$TLS_KEY_PASS_DEV -out $KEY_NAME 4096
          sudo chown root:root $KEY_NAME
          sudo chmod 600 $KEY_NAME
          sudo openssl req -new -key $KEY_NAME -out $CRS_NAME -subj "/C=CA/ST=Ontario/L=Toronto/O=NA/OU=NA/CN=$DOMAIN_NAME"
        
        env:
          TLS_KEY_PASS_DEV: ${{ secrets.TLS_KEY_PASS_DEV }}
          DOMAIN_NAME: ${{ needs.Get-Domain.outputs.domain }}

      - name: setup ssh connection to ec2
        if: ${{ steps.https-check.outputs.HTTPS_ENABLED == 'false' }}
        run: |
          SSH_DIR=~/.ssh
          mkdir -p $SSH_DIR
          chmod 700 $SSH_DIR
          cd $SSH_DIR
          ssh-keyscan $EC2_IP > known_hosts
          echo "$SSH_KEY" > $SSH_PRIVATE_KEY_FILE
          chmod 600 *
          eval `ssh-agent -s`
          ssh-add ${SSH_DIR}/${SSH_PRIVATE_KEY_FILE}

        env:
          EC2_IP: ${{ needs.Get-EC2-IP.outputs.ec2-ip }}
          SSH_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          SSH_PRIVATE_KEY_FILE: id_rsa
      
      - name: setup yq
        if: ${{ steps.https-check.outputs.HTTPS_ENABLED == 'false' }} 
        uses: mikefarah/yq@master

      - name: checkout repo
        if: ${{ steps.https-check.outputs.HTTPS_ENABLED == 'false' }}
        uses: actions/checkout@v4
      
      - name: setup https
        if: ${{ steps.https-check.outputs.HTTPS_ENABLED == 'false' }}
        run: |
          ssh ${EC2_USERNAME}@${EC2_IP}
          curl --silent https://raw.githubusercontent.com/srvrco/getssl/latest/getssl > getssl ; chmod 700 getssl
          ./getssl -c $DOMAIN_NAME
          sed -i -E 's/#ACCOUNT_EMAIL="[^"]*"/ACCOUNT_EMAIL="${DOMAIN_EMAIL}"/' .getssl/getssl.cfg
          ENVIRONMENT=$(yq '.app.environment' /envs/testing/deployment.yml)
          if[[ "$ENVIRONMENT" = "production" ]]; then
            sed -i 's/CA="https://acme-staging-v02.api.letsencrypt.org"/#CA="https://acme-staging-v02.api.letsencrypt.org"/' .getssl/getssl.cfg
            sed -i 's/#CA="https://acme-v02.api.letsencrypt.org"/CA="https://acme-v02.api.letsencrypt.org"/' .getssl/getssl.cfg
          fi
          sed -i -E 's/#DOMAIN_PEM_LOCATION="[^"]*"/DOMAIN_PEM_LOCATION="${KEY_DIRECTORY}${CRS_NAME}"/' .getssl/getssl.cfg
          getssl $DOMAIN_NAME

        env:
          EC2_USERNAME: ${{ secrets.EC2_USERNAME_DEV  }}
          EC2_IP: ${{ needs.Get-EC2-IP.outputs.ec2-ip }}
          DOMAIN_NAME: ${{ needs.Get-Domain.outputs.domain }}
          DOMAIN_EMAIL: ${{ secrets.DOMAIN_EMAIL }}

  Set-Version-In-Repo:
    runs-on: ubuntu-latest
    needs: EC2-Deploy

    env:
      VERSION_CONFIG: envs/testing/version.yml
      BRANCH: main

    steps:
      - name: setup yq
        uses: mikefarah/yq@master

      - name: checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ env.VERSION_CONFIG }}
          sparse-checkout-cone-mode: false
      
      - name: update version and build if outdated
        run: |
          CURRENT_VERSION=$(yq '.app-version' ${{ env.VERSION_CONFIG }})
          CURRENT_BUILD=$(yq '.build' ${{ env.VERSION_CONFIG }})
          HAS_FILE_BEEN_UPDATED="false"
          if [[ ! "$CURRENT_VERSION" = "$VERSION" ]]; then
            version=$VERSION yq -i '.app-version = env(version)' ${{ env.VERSION_CONFIG }}
            HAS_FILE_BEEN_UPDATED="true"
          fi
          if [[ ! $CURRENT_BUILD -eq $BUILD ]]; then
            build=$BUILD yq -i '.build = env(build)' ${{ env.VERSION_CONFIG }}
            HAS_FILE_BEEN_UPDATED="true"
          fi
          if [[ "$HAS_FILE_BEEN_UPDATED" = "true" ]]; then
            git config --global user.email ${{ secrets.ACTIONS_COMMIT_EMAIL}}
            git config --global user.name ${{ secrets.ACTIONS_COMMIT_NAME }}
            git add ${{ env.VERSION_CONFIG }}
            git commit -m "Set version according to image via Github Actions"
            git push origin $GITHUB_REF_NAME
          fi

        env:
          BUILD: ${{ needs.EC2-Deploy.outputs.build }}
          VERSION: ${{ needs.EC2-Deploy.outputs.version }}
